apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMVENDQXBXZ0F3SUJBZ0lSQU5JNkxPSlhVYUdRd0JQZGo2amJHMG93RFFZSktvWklodmNOQVFFTEJRQXcKTHpFdE1Dc0dBMVVFQXhNa1pURXhZbVZoTldFdE5HVXpNUzAwTURZNUxXRTNNelF0TldJeFpEWmxaV1ZoWmprMQpNQ0FYRFRJMU1URXdOVEl6TkRBek5Wb1lEekl3TlRVeE1ETXdNREEwTURNMVdqQXZNUzB3S3dZRFZRUURFeVJsCk1URmlaV0UxWVMwMFpUTXhMVFF3TmprdFlUY3pOQzAxWWpGa05tVmxaV0ZtT1RVd2dnR2lNQTBHQ1NxR1NJYjMKRFFFQkFRVUFBNElCandBd2dnR0tBb0lCZ1FDaXFNaXRPbW5aS2Y5eVd6TE05WmIxRG9pU1VrYXQzMDZXRUF2Vgp5c3FyRHg2YmJHNGhLMnhrYXlpOVpGcWtRVTZBMmhpU1REV0k0UkFZM1RmSjFWL1d5V2JyczRrbEdua1I3dDRlClhzUitESzBubzUzeTB0SExMMGE3aWRlRm1jSHRFMzFNODZEa0h5UENQZi95WU1YMVgvZGQ1VDQvcVlSS1pKMjgKb3RTbUNWTy9lNkNqM2RQcUQ1dWdaQUkwcnV0b2I2MlNkVzR1eThSaHhCaGxIYjA5MFFVOCtjOHJmdHcwUUp1MwpockR3WlV6U3BLek9ramZuNHFubUVBZjk3U0hrVGk0Y00zUC90Ky9mVXl6S05YU2Y4ZzBkWGlTQ0RPeUlNbENoCjZIZVc1TEY3UUFkVkswWEY2bjc4di9ZU2Z6SDBiSm5tb285OFNDdE5NSWMzamR4eisvUXd1MVZxZjVUTUpJa0EKL2pjL0dCa3R3dW00VlZjcUdtaGYzRjVTaEpFTUQ0YUdycjJQMFdBT25rajFmbXRPRjFiY1I3N3lQSDU4Nyt4RQpob3VkRlBJSlVUUlZtSUVHSFg1bUVsTEcwOUc0VnhDWEhoWEdCaU0yaTRFT003VkJ1b3p6a3NDSWgxakQ4YjhICnJReFZSUHNOcU9DZHNxRkZ0emJJS1NPcWRVTUNBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdJRU1BOEcKQTFVZEV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGSG0rVC9RVXpYUkVLMlE5TVB5Z0wrU2tuZHVMTUEwRwpDU3FHU0liM0RRRUJDd1VBQTRJQmdRQUhNYm0wb2tIeHJheldaZ1YxMlNpNE52VXFJbGhJR0tOVTFFemRLSHpuCjZRd3lhYk51ZXMvcmNvQU5RYW4xSGlIaEZaU2dMSnhEYW5xWCs5Q0FlVk5XOWdQRGJyVUVnaDJrZkRsWFAwZk0KYlB6TkZmWWROeXh6c2VGbHhjeWJuQXIrM3ZLVWRWakpqbmtsK3JNZEZDOW1VS1NEaERpOGY2S1U1eWRvVGlragp0d2g5bCs2MWF0aks3RFlGdTE4OUl2bXFMcFZOVW85NnBVcDl5anlKS2JPTGhCbTN2MXZtVjNLU1JWQkk4TWZLCm0rVm5nSTVjcndoWC9wM1AvekhCS0lGSWtDN05Pb2pBY3h5U2tuTFJJbU14VkxSWEtuVzRBZGxJQ1pQU0EvRXQKU1ZKUGc3TXRPRW1oNUhpWkd1dTN2QzhTVHRsRXBXSk1yd3FudWVLdDlpdmFXM2x3WXNVTERpcXl4bC9xK0JIWgo1MFFWQnpNVWhWS1RSNzk0TUVObzIxcXphYjZhaFU5Y0Eyb1RJMjduUTBoL1dhTjRsaHIxOXcxNklHTXR3dityClZUVURITjE5ekVmQmpmbFA1TDByamNmYlhCOVBFSkw5QlZOSVlsRStXZlc0RGQ5ZEtUOFZYbCtNVUFnM1hBY3AKTld1eTFPZVJKN1prbHJsTWFkOWsxZ0U9Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    server: https://34.55.219.226
  name: autoscaling-lab-476403_us-central1_demo-autopilot
contexts:
- context:
    cluster: autoscaling-lab-476403_us-central1_demo-autopilot
    user: autoscaling-lab-476403_us-central1_demo-autopilot
  name: autoscaling-lab-476403_us-central1_demo-autopilot
current-context: autoscaling-lab-476403_us-central1_demo-autopilot
kind: Config
preferences: {}
users:
- name: autoscaling-lab-476403_us-central1_demo-autopilot
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: gke-gcloud-auth-plugin
      installHint: Install gke-gcloud-auth-plugin via gcloud components.
      provideClusterInfo: true

